# Generated by Django 2.2.7 on 2019-11-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('html_url', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=512, null=True)),
                ('private', models.BooleanField()),
                ('created_at', models.CharField(max_length=200)),
                ('watchers', models.IntegerField()),
                ('username', models.CharField(max_length=200)),
            ],
        ),
    ]
